# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# xxxxx

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration)'
    zipAfterPublish: false
- task: CopyFiles@2
  displayName: 'Copy Console App to WebJob Location'
  inputs:
    SourceFolder: WebJobsSDKSample/bin/Release/netcoreapp3.1
    TargetFolder: pipelines-dotnet-core/bin/Release/netcoreapp2.2/publish/App_Data/jobs/triggered/app
- task: ArchiveFiles@2
  displayName: 'Archive WebApp'
  inputs:
    rootFolderOrFile: pipelines-dotnet-core\bin\Release\netcoreapp2.2\publish
    includeRootFolder: false
    archiveFile: pipelines-dotnet-core\bin\Release\netcoreapp2.2\pipelines-dotnet-core.zip
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'test connection 1'
    appName: 'WebApplication120200310093243'
    package: $(System.ArtifactsDirectory)/**/*.zip
